osConfigs:
  - name: Linux
    value: linux
    options:
    - name: RedHat Enterprise Linux 8.4
      value: RHEL8u4
    - name: RedHat Enterprise Linux 7.9
      value: RHEL7u9
    environments:
      - name: Pre-Producton
        value: preprod
        regions:
          - name: Canada
            value: CA
          - name: United States
            value: US
        domains:
          - devfg.rbc.com
          - saifg.rbc.com
        resourceSizes:
          - name: Small
            value: small
            cpu: 2.0
            memory: 8
            disk: 250
          - name: Medium
            value: medium
            cpu: 4.0
            memory: 16
            disk: 250
          - name: Large
            value: large
            cpu: 4.0
            memory: 16
            disk: 250
    software:
      options:
        - name: Java 8 SDK
          value: java_8
        - name: Apache Web Server
          value: apache   
  - name: Windows
    value: windows
    configs:
    - name: Windows Server 2019 Standard
      value: W2019Std
    - name: Windows Server 2016 Standard
      value: W2016Std
    environments:
      - name: Pre-Producton
        value: preprod
        regions:
          - name: Canada
            value: CA
        domains:
          - devfg.rbc.com
          - saifg.rbc.com
        resourceSizes:
          - name: Small
            value: small
            cpu: 2.0
            memory: 8
            disk: 250
          - name: Medium
            value: medium
            cpu: 4.0
            memory: 16
            disk: 250
          - name: Large
            value: large
            cpu: 4.0
            memory: 16
            disk: 250
    software:
      options:
        - name: Internet Information Services (IIS)
          value: iis